/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.ItemEvent;

/**
 *
 * @author bgood_000
 */
public class Setup extends javax.swing.JFrame {

    /**
     * Creates new form Setup
     */
    public Setup() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        setupTabPane = new javax.swing.JTabbedPane();
        gameBoardTabPanel = new javax.swing.JPanel();
        cardDecksTabPanel = new javax.swing.JPanel();
        playersTabPanel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        rulesTabPanel = new javax.swing.JPanel();
        jailRulesPanel = new javax.swing.JPanel();
        bailFeeField = new javax.swing.JFormattedTextField();
        speedLimitField = new javax.swing.JFormattedTextField();
        enableSpeeding = new javax.swing.JCheckBox();
        maxJailTermField = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        propertyRulesPanel = new javax.swing.JPanel();
        mortgageInterestRateField = new javax.swing.JFormattedTextField();
        hotelPrerequisiteField = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        enableFiniteResources = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        hotelAmount = new javax.swing.JFormattedTextField();
        enableEvenBuild = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        improvementDepreciationField = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        setCompletionBonusField = new javax.swing.JFormattedTextField();
        enableMortgageInterest = new javax.swing.JCheckBox();
        houseAmount = new javax.swing.JFormattedTextField();
        cashRulesPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        enableGoLandingBonus = new javax.swing.JCheckBox();
        enableBonusCap = new javax.swing.JCheckBox();
        enableFreeParkingBonus = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        passGoBonus = new javax.swing.JFormattedTextField();
        goLandingBonusValue = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        bonusCapAmountField = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        configItems = new javax.swing.JComboBox<>();

        jTextField1.setText("jTextField1");

        jLabel2.setText("jLabel2");

        jCheckBox2.setText("jCheckBox2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout gameBoardTabPanelLayout = new javax.swing.GroupLayout(gameBoardTabPanel);
        gameBoardTabPanel.setLayout(gameBoardTabPanelLayout);
        gameBoardTabPanelLayout.setHorizontalGroup(
            gameBoardTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );
        gameBoardTabPanelLayout.setVerticalGroup(
            gameBoardTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
        );

        setupTabPane.addTab("Game Board", gameBoardTabPanel);

        javax.swing.GroupLayout cardDecksTabPanelLayout = new javax.swing.GroupLayout(cardDecksTabPanel);
        cardDecksTabPanel.setLayout(cardDecksTabPanelLayout);
        cardDecksTabPanelLayout.setHorizontalGroup(
            cardDecksTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );
        cardDecksTabPanelLayout.setVerticalGroup(
            cardDecksTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
        );

        setupTabPane.addTab("Card Decks", cardDecksTabPanel);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton3.setText("+");
        jButton3.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton3.setMaximumSize(new java.awt.Dimension(23, 23));
        jButton3.setMinimumSize(new java.awt.Dimension(23, 23));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField2.setText("jTextField2");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout playersTabPanelLayout = new javax.swing.GroupLayout(playersTabPanel);
        playersTabPanel.setLayout(playersTabPanelLayout);
        playersTabPanelLayout.setHorizontalGroup(
            playersTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playersTabPanelLayout.createSequentialGroup()
                .addGroup(playersTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(playersTabPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(playersTabPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(414, Short.MAX_VALUE))
        );
        playersTabPanelLayout.setVerticalGroup(
            playersTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playersTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        setupTabPane.addTab("Players", playersTabPanel);

        bailFeeField.setText("50");

        speedLimitField.setText("3");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, enableSpeeding, org.jdesktop.beansbinding.ELProperty.create("${selected}"), speedLimitField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        enableSpeeding.setSelected(true);
        enableSpeeding.setText("Jail by Speeding");

        maxJailTermField.setText("3");

        jLabel5.setText("Speed Limit");

        jLabel11.setText("Maximum Jail Term");

        jLabel12.setText("Bail Fee");

        javax.swing.GroupLayout jailRulesPanelLayout = new javax.swing.GroupLayout(jailRulesPanel);
        jailRulesPanel.setLayout(jailRulesPanelLayout);
        jailRulesPanelLayout.setHorizontalGroup(
            jailRulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jailRulesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jailRulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enableSpeeding)
                    .addGroup(jailRulesPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(speedLimitField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(jailRulesPanelLayout.createSequentialGroup()
                        .addGroup(jailRulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bailFeeField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maxJailTermField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jailRulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jailRulesPanelLayout.setVerticalGroup(
            jailRulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jailRulesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enableSpeeding)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jailRulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(speedLimitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jailRulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxJailTermField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jailRulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bailFeeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap())
        );

        mortgageInterestRateField.setText("10");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, enableMortgageInterest, org.jdesktop.beansbinding.ELProperty.create("${selected}"), mortgageInterestRateField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        hotelPrerequisiteField.setText("4");
        hotelPrerequisiteField.setMaximumSize(new java.awt.Dimension(40, 20));
        hotelPrerequisiteField.setMinimumSize(new java.awt.Dimension(40, 20));
        hotelPrerequisiteField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelPrerequisiteFieldActionPerformed(evt);
            }
        });

        jLabel9.setText("Improvement Depreciation");

        jLabel8.setText("Hotel Requirement");

        enableFiniteResources.setSelected(true);
        enableFiniteResources.setText("Finite Resources");

        jLabel7.setText("Hotels");

        hotelAmount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        hotelAmount.setText("12");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, enableFiniteResources, org.jdesktop.beansbinding.ELProperty.create("${selected}"), hotelAmount, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        enableEvenBuild.setSelected(true);
        enableEvenBuild.setText("Even-Build Improvments");

        jLabel10.setText("Completion Rent Bonus");

        improvementDepreciationField.setText("2");

        jLabel6.setText("Houses");

        jLabel13.setText("Interest Rate");

        setCompletionBonusField.setText("2");
        setCompletionBonusField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setCompletionBonusFieldActionPerformed(evt);
            }
        });

        enableMortgageInterest.setSelected(true);
        enableMortgageInterest.setText("Mortgage Interest");

        houseAmount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        houseAmount.setText("32");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, enableFiniteResources, org.jdesktop.beansbinding.ELProperty.create("${selected}"), houseAmount, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout propertyRulesPanelLayout = new javax.swing.GroupLayout(propertyRulesPanel);
        propertyRulesPanel.setLayout(propertyRulesPanelLayout);
        propertyRulesPanelLayout.setHorizontalGroup(
            propertyRulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertyRulesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(propertyRulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(propertyRulesPanelLayout.createSequentialGroup()
                        .addGroup(propertyRulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enableMortgageInterest)
                            .addComponent(enableFiniteResources)
                            .addGroup(propertyRulesPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(propertyRulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(propertyRulesPanelLayout.createSequentialGroup()
                                        .addGroup(propertyRulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(hotelAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                            .addComponent(houseAmount))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(propertyRulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)))
                                    .addGroup(propertyRulesPanelLayout.createSequentialGroup()
                                        .addComponent(mortgageInterestRateField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13))))
                            .addGroup(propertyRulesPanelLayout.createSequentialGroup()
                                .addComponent(hotelPrerequisiteField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addComponent(enableEvenBuild))
                        .addGap(44, 44, 44))
                    .addGroup(propertyRulesPanelLayout.createSequentialGroup()
                        .addGroup(propertyRulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(improvementDepreciationField, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(setCompletionBonusField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(propertyRulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        propertyRulesPanelLayout.setVerticalGroup(
            propertyRulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertyRulesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enableFiniteResources)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(propertyRulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(houseAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(propertyRulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hotelAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(enableEvenBuild)
                .addGap(18, 18, 18)
                .addGroup(propertyRulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hotelPrerequisiteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(propertyRulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(improvementDepreciationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(propertyRulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setCompletionBonusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(enableMortgageInterest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(propertyRulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mortgageInterestRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jLabel1.setText("Pass GO Bonus");

        enableGoLandingBonus.setText("Land on GO Bonus");

        enableBonusCap.setText("Bonus Cap");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, enableFreeParkingBonus, org.jdesktop.beansbinding.ELProperty.create("${selected}"), enableBonusCap, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        enableFreeParkingBonus.setSelected(false);
        enableFreeParkingBonus.setText("Free Parking Bonus");
        enableFreeParkingBonus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enableFreeParkingBonusActionPerformed(evt);
            }
        });

        jLabel4.setText("Amount");

        passGoBonus.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        passGoBonus.setText("200");
        passGoBonus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passGoBonusActionPerformed(evt);
            }
        });

        goLandingBonusValue.setText("200");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, enableGoLandingBonus, org.jdesktop.beansbinding.ELProperty.create("${selected}"), goLandingBonusValue, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jLabel3.setText("Amount");

        bonusCapAmountField.setText("500");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, enableBonusCap, org.jdesktop.beansbinding.ELProperty.create("${selected}"), bonusCapAmountField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout cashRulesPanelLayout = new javax.swing.GroupLayout(cashRulesPanel);
        cashRulesPanel.setLayout(cashRulesPanelLayout);
        cashRulesPanelLayout.setHorizontalGroup(
            cashRulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cashRulesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cashRulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cashRulesPanelLayout.createSequentialGroup()
                        .addComponent(passGoBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addComponent(enableGoLandingBonus)
                    .addComponent(enableFreeParkingBonus)
                    .addGroup(cashRulesPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(cashRulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cashRulesPanelLayout.createSequentialGroup()
                                .addComponent(goLandingBonusValue, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addComponent(enableBonusCap)
                            .addGroup(cashRulesPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(bonusCapAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)))))
                .addGap(14, 14, 14))
        );
        cashRulesPanelLayout.setVerticalGroup(
            cashRulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cashRulesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cashRulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passGoBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(enableGoLandingBonus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cashRulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(goLandingBonusValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(enableFreeParkingBonus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enableBonusCap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cashRulesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bonusCapAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout rulesTabPanelLayout = new javax.swing.GroupLayout(rulesTabPanel);
        rulesTabPanel.setLayout(rulesTabPanelLayout);
        rulesTabPanelLayout.setHorizontalGroup(
            rulesTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rulesTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cashRulesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(propertyRulesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jailRulesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        rulesTabPanelLayout.setVerticalGroup(
            rulesTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rulesTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rulesTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(propertyRulesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(rulesTabPanelLayout.createSequentialGroup()
                        .addComponent(jailRulesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cashRulesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        setupTabPane.addTab("Rules", rulesTabPanel);

        jButton1.setText("Reset to Default");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        configItems.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(configItems, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
            .addComponent(setupTabPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(setupTabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(configItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passGoBonusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passGoBonusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passGoBonusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //default rules
        passGoBonus.setText("200");
        enableGoLandingBonus.setSelected(false);
        enableFreeParkingBonus.setSelected(false);
        enableBonusCap.setSelected(false);
        enableFiniteResources.setSelected(true);
        houseAmount.setText("32");
        hotelAmount.setText("12");
        enableEvenBuild.setSelected(true);
        hotelPrerequisiteField.setText("4");
        improvementDepreciationField.setText("2");
        setCompletionBonusField.setText("2");
        enableMortgageInterest.setSelected(true);
        mortgageInterestRateField.setText("10");
        enableSpeeding.setSelected(true);
        speedLimitField.setText("3");
        maxJailTermField.setText("3");
        bailFeeField.setText("50");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void enableFreeParkingBonusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enableFreeParkingBonusActionPerformed
        if (enableBonusCap.isSelected() == true) {
            enableBonusCap.setSelected(false);
        }
        if (enableFreeParkingBonus.isSelected() == true) {
            enableBonusCap.setEnabled(true);
        } else if (enableFreeParkingBonus.isSelected() == false) {
            enableBonusCap.setEnabled(false);
        }
    }//GEN-LAST:event_enableFreeParkingBonusActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void hotelPrerequisiteFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelPrerequisiteFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hotelPrerequisiteFieldActionPerformed

    private void setCompletionBonusFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setCompletionBonusFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setCompletionBonusFieldActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Setup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Setup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Setup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Setup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Setup().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField bailFeeField;
    private javax.swing.JFormattedTextField bonusCapAmountField;
    private javax.swing.JPanel cardDecksTabPanel;
    private javax.swing.JPanel cashRulesPanel;
    private javax.swing.JComboBox<String> configItems;
    private javax.swing.JCheckBox enableBonusCap;
    private javax.swing.JCheckBox enableEvenBuild;
    private javax.swing.JCheckBox enableFiniteResources;
    private javax.swing.JCheckBox enableFreeParkingBonus;
    private javax.swing.JCheckBox enableGoLandingBonus;
    private javax.swing.JCheckBox enableMortgageInterest;
    private javax.swing.JCheckBox enableSpeeding;
    private javax.swing.JPanel gameBoardTabPanel;
    private javax.swing.JFormattedTextField goLandingBonusValue;
    private javax.swing.JFormattedTextField hotelAmount;
    private javax.swing.JFormattedTextField hotelPrerequisiteField;
    private javax.swing.JFormattedTextField houseAmount;
    private javax.swing.JFormattedTextField improvementDepreciationField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel jailRulesPanel;
    private javax.swing.JFormattedTextField maxJailTermField;
    private javax.swing.JFormattedTextField mortgageInterestRateField;
    private javax.swing.JFormattedTextField passGoBonus;
    private javax.swing.JPanel playersTabPanel;
    private javax.swing.JPanel propertyRulesPanel;
    private javax.swing.JPanel rulesTabPanel;
    private javax.swing.JFormattedTextField setCompletionBonusField;
    private javax.swing.JTabbedPane setupTabPane;
    private javax.swing.JFormattedTextField speedLimitField;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
